language: python

python:
  - 3.5
  - 3.6

before_script: rm --recursive --force --verbose *.py[cod]

install: pip install coveralls

script: coverage run --source=notas.utils -m unittest

after_success: coveralls